name: feature-ci

on:
  push:
    branches:
      - 'feature/**'

  pull_request:
    branches:
      - 'feature/**'

env:
  ENV_CHECKOUT_CACHE: 'npm'
  ENV_NODE_VERSION: '16.x'
  ENV_REGISTRY_URL: 'https://npm.pkg.github.com'
  ENV_NODE_ENV: 'production'

jobs:
  validate-git:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Validate secrets, passwords, URLs exposed in commits
        run: |
          git log --patch --no-merges -S 'password' -S 'secret' -S 'https://'
          if [ $? -eq 0 ]; then
            echo "Error: Secrets, passwords, or URLs exposed in commits."
            exit 1
          fi

      - name: Validate secrets, passwords, URLs exposed in project files
        run: |
          git grep -E 'password|secret|https://'
          if [ $? -eq 0 ]; then
            echo "Error: Secrets, passwords, or URLs exposed in project files."
            exit 1
          fi

      - name: Validate if commit follows the pattern in description "#<number> - description"
        run: |
          if ! git log -1 --pretty=%B | grep -qE '^#[0-9]+ - .+'; then
            echo "Error: Commit description does not follow the pattern '#<number> - description'"
            exit 1
          fi

  validate-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Validate package.json
        run: |
          PACKAGE_NAME=$(cat package.json | jq -r '.name')
          PRIVATE=$(cat package.json | jq -r '.private')
          PUBLISH_CONFIG=$(cat package.json | jq '.publishConfig')
          REPOSITORY=$(cat package.json | jq '.repository')
          VERSION=$(cat package.json | jq -r '.version')

          if [[ ! ${PACKAGE_NAME} =~ ^@[a-zA-Z0-9_-]+/[a-zA-Z0-9_-]+$ ]]; then
            echo "Error: attribute name is not in the format @<company>/<name>"
            exit 1
          fi

          if [[ ${PUBLISH_CONFIG} == "null" ]]; then
            echo "Error: publishConfig is required"
            exit 1
          fi

          if [[ ${REPOSITORY} == "null" ]]; then
            echo "Error: repository is required"
            exit 1
          fi

          if [[ ${PRIVATE} == "true" ]]; then
            echo "Warning: private attribute is set to true, changing to false"
            jq '.private = false' package.json > package.json.tmp && mv package.json.tmp package.json
          fi

          echo "VERSION=${VERSION}" >> $GITHUB_ENV

  packages:
    timeout-minutes: 1
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.ENV_NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

  audit-packages:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Audit Packages
        run: npm audit --audit-level moderate
        env:
          CI: true

  lint:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    needs: [ packages, audit-packages ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.ENV_NODE_VERSION }}

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  unit-test:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    needs: [ packages, audit-packages ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.ENV_NODE_VERSION }}

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run test

  e2e:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    needs: [ packages, audit-packages ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.ENV_NODE_VERSION }}

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run test:e2e

  coverage:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    needs: [ packages, audit-packages ]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.ENV_NODE_VERSION }}

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Install Dependencies
        run: npm ci

      - name: Lint
        run: npm run test:cov

  codeql:
    timeout-minutes: 5
    needs: [ unit-test, e2e, coverage, lint ]
    runs-on: ubuntu-latest

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.ENV_NODE_VERSION }}

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript

      - run: |
          npm ci
          npm run build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2

  build-and-push-package:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    needs: [ unit-test, e2e, coverage ]

    permissions:
      contents: read
      packages: write

    steps:

      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configurar Git
        run: |
          git config --global user.name "Github Actions"
          git config --global user.email "actions@github.com"

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.ENV_NODE_VERSION }}

      - name: Restore Cached Dependencies
        uses: actions/cache@v3
        id: npm-cache
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Get Package Version
        run: |
          export VERSION=$(node -p "require('./package.json').version")-sha.${{github.sha}}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Update version
        run: npm version ${{ env.VERSION }}

      - name: Install Dependencies
        run: npm ci

      - name: Build Artifact
        run: npm run build
        env:
          NODE_ENV: ${{ env.ENV_NODE_ENV }}

      - name: Publish Artifact to Github Packages
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.ENV_NODE_VERSION }}
          registry-url: ${{ env.ENV_REGISTRY_URL }}
          scope: ${{ github.repository_owner }}
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-image:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    needs: [ build-and-push-package ]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  scan-vulnerability-image:
    timeout-minutes: 10
    continue-on-error: true
    runs-on: ubuntu-latest
    needs: [ build-and-push-image ]

    permissions:
      contents: read
      packages: write

    steps:
      - name: Scan vulnerability from Github Packages
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: image
          image-ref: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:sha-${{ github.sha }}
          format: 'sarif'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'