name: feature-ci

on:
  push:
    branches:
      - 'feature/*'
  pull_request:
    branches:
      - 'feature/*'

jobs:

  analyze-code:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x, 18.x]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm ci
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Eslint
        run: npm run lint
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

      - name: Unit Tests
        run: npm test
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'

  build:
    runs-on: ubuntu-latest
    needs: [analyze-code]
    steps:
      - name: Build Artifact
        run: npm run build
        env:
          NODE_ENV: 'production'
